export const IndianStates = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Lakshadweep',
  'Delhi',
  'Puducherry',
  'Ladakh',
  'Jammu and Kashmir',
];

export const IndianCities: Record<string, string[]> = {
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Tirupati',
    'Kakinada',
  ],
  'Arunachal Pradesh': ['Itanagar', 'Naharlagun', 'Pasighat'],
  Assam: [
    'Guwahati',
    'Silchar',
    'Nagaon',
    'Sonitpur',
    'Tezpur',
    'Bongaigaon',
    'Dibrughar',
  ],
  Bihar: [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Madhubani',
    'Muzaffarpur',
    'Darbhanga',
    'Purnia',
    'Araria',
  ],
  Chhattisgarh: [
    'Raipur',
    'Bilaspur',
    'Durg',
    'Rajnandgaon',
    'Raigarh',
    'Korba',
    'Jagdalpur',
  ],
  Goa: ['Panaji', 'Vasco da Gama', 'Margao', 'Mapusa', 'Ponda'],
  Gujarat: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Jamnagar',
    'Bhavnagar',
    'Anand',
    'Gandhinagar',
  ],
  Haryana: [
    'Faridabad',
    'Gurgaon',
    'Hisar',
    'Rohtak',
    'Ambala',
    'Panipat',
    'Karnal',
    'Yamunanagar',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Solan',
    'Mandi',
    'Kangra',
    'Kullu',
    'Bilaspur',
    'Palampur',
  ],
  Jharkhand: [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Giridih',
    'Bokaro',
    'Hazaribagh',
    'Dumka',
  ],
  Karnataka: [
    'Bangalore',
    'Belagavi',
    'Mangalore',
    'Mysore',
    'Hubli',
    'Davanagere',
    'Belgaum',
    'Shimoga',
  ],
  Kerala: [
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Thrissur',
    'Alappuzha',
    'Kottayam',
    'Kannur',
    'Pathanamthitta',
  ],
  'Madhya Pradesh': [
    'Indore',
    'Bhopal',
    'Jabalpur',
    'Ujjain',
    'Sagar',
    'Gwalior',
    'Ratlam',
    'Vidisha',
  ],
  Maharashtra: [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Aurangabad',
    'Solapur',
    'Nashik',
    'Kolhapur',
  ],
  Manipur: ['Imphal', 'Thoubal', 'Senapati', 'Bishnupur'],
  Meghalaya: ['Shillong', 'Tura', 'Nongstoin', 'Jowai'],
  Mizoram: ['Aizawl', 'Lunglei', 'Saiha'],
  Nagaland: ['Kohima', 'Dimapur', 'Wokha', 'Mon'],
  Odisha: [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Sambalpur',
    'Baripada',
    'Bhilai',
    'Koraput',
  ],
  Punjab: [
    'Chandigarh',
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali',
  ],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Udaipur',
    'Kota',
    'Ajmer',
    'Bikaner',
    'Alwar',
    'Pali',
  ],
  Sikkim: ['Gangtok', 'Namchi', 'Gyalshing', 'Mangan'],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Salem',
    'Trichy',
    'Erode',
    'Tiruppur',
    'Nagercoil',
  ],
  Telangana: [
    'Hyderabad',
    'Warangal',
    'Vijayawada',
    'Karimnagar',
    'Ramagundam',
    'Khammam',
    'Nizamabad',
  ],
  Tripura: ['Agartala', 'Udaipur', 'Dharmanagar', 'Ambassa'],
  'Uttar Pradesh': [
    'Agra',
    'Aligarh',
    'Ambedkar Nagar',
    'Amethi',
    'Amroha',
    'Auraiya',
    'Ayodhya',
    'Azamgarh',
    'Baghpat',
    'Bahraich',
    'Ballia',
    'Balrampur',
    'Banda',
    'Barabanki',
    'Bareilly',
    'Basti',
    'Bhadohi',
    'Bijnor',
    'Bulandshahr',
    'Chandauli',
    'Chitrakoot',
    'Deoria',
    'Etah',
    'Etawah',
    'Farrukhabad',
    'Fatehpur',
    'Firozabad',
    'Gautam Buddha Nagar',
    'Ghaziabad',
    'Gonda',
    'Gorakhpur',
    'Hamirpur',
    'Hapur',
    'Hardoi',
    'Hathras',
    'Jalaun',
    'Jaunpur',
    'Jhansi',
    'Kannauj',
    'Kanpur Dehat',
    'Kanpur Nagar',
    'Kasganj',
    'Kaushambi',
    'Kushinagar',
    'Lalitpur',
    'Lucknow',
    'Maharajganj',
    'Mahoba',
    'Mainpuri',
    'Mathura',
    'Mau',
    'Meerut',
    'Mirzapur',
    'Moradabad',
    'Muzaffarnagar',
    'Pilibhit',
    'Prayagraj',
    'Pratapgarh',
    'Rampur',
    'Saharanpur',
    'Sambhal',
    'Sant Kabir Nagar',
    'Shahjahanpur',
    'Shamli',
    'Shravasti',
    'Siddharthnagar',
    'Sitapur',
    'Sonbhadra',
    'Sultanpur',
    'Unnao',
    'Varanasi',
  ],
  Uttarakhand: [
    'Dehradun',
    'Haridwar',
    'Rishikesh',
    'Nainital',
    'Almora',
    'Bageshwar',
    'Pithoragarh',
  ],
  'West Bengal': [
    'Kolkata',
    'Darjeeling',
    'Siliguri',
    'Asansol',
    'Durgapur',
    'Kharagpur',
    'Haldia',
    'Burdwan',
  ],
  'Andaman and Nicobar Islands': ['Port Blair', 'Car Nicobar'],
  Chandigarh: ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Silvassa',
    'Daman',
    'Diu',
    'Dadra',
  ],
  Lakshadweep: ['Kavaratti', 'Agatti', 'Minicoy'],
  Delhi: ['New Delhi', 'Old Delhi', 'East Delhi', 'West Delhi', 'South Delhi'],
  Puducherry: ['Puducherry', 'Karaikal', 'Yanam', 'Mahe'],
  Ladakh: ['Leh', 'Kargil'],
  'Jammu and Kashmir': ['Srinagar', 'Jammu', 'Anantnag', 'Sopore', 'Baramulla'],
};

export const getCitiesByState = (state: string): string[] => {
  return IndianCities[state] || [];
};
